<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ulquria" failures="1" tests="10" name="Surefire test" time="24.998" errors="0" timestamp="2025-10-25T16:16:03 IST">
  <testcase classname="api.test.DDTests" name="testPostuser" time="4.937"/>
  <testcase classname="api.test.DDTests" name="testPostuser" time="1.596"/>
  <testcase classname="api.test.DDTests" name="testPostuser" time="1.533"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.548"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.638"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.534"/>
  <testcase classname="api.test.UserTests" name="testPostUser" time="1.622"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="1.578"/>
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="3.202"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.612">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testDeleteUserByName(UserTests.java:103)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- Surefire test -->
